# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 11:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('height_feet', models.CharField(help_text="Format: F'II e.g. 6'01 or 5'11", max_length=4, validators=[django.core.validators.RegexValidator("^[0-9']*$", "Format must be e.g. 6'01")])),
                ('height_meters', models.DecimalField(decimal_places=2, help_text='Format: e.g. 1.83', max_digits=3)),
                ('hair_colour', models.CharField(choices=[('auburn', 'Auburn'), ('black', 'Black'), ('blond', 'Blond(e)'), ('darkbrown', 'Dark Brown'), ('fair', 'Fair'), ('grey', 'Grey'), ('greying', 'Greying'), ('lightbrown', 'Light/Mid Brown'), ('red', 'Red/Titian'), ('salt', 'Salt & Pepper'), ('sandy', 'Sandy'), ('silver', 'Silver'), ('strawblond', 'Strawberry Blonde'), ('white', 'White')], default='strawblonde', max_length=10)),
                ('eye_colour', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('bluegreen', 'Blue-Green'), ('bluegrey', 'Blue-Grey'), ('brown', 'Brown'), ('green', 'Green'), ('grey', 'Grey'), ('greygreen', 'Grey-Green'), ('hazel', 'Hazel'), ('hbluebrown', 'Heterochromia - blue/brown'), ('hgreenblue', 'Heterochromia - green/blue'), ('hgreenbrown', 'Heterochromia - green/brown'), ('hbluehazel', 'Heterochromia - blue/blue-hazel'), ('hcgreen', 'Heterochromia - Central Green'), ('hspecial', 'Heterochromia - distinct green and brown areas in both eyes'), ('lightblue', 'Light Blue')], default='brown', max_length=10)),
                ('playing_age_min', models.IntegerField()),
                ('playing_age_max', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="E.g. 'Professional' or 'Personal'", max_length=32)),
                ('email', models.EmailField(help_text='E.g. patrickstewart@gmail.com', max_length=128)),
                ('phone', models.CharField(blank=True, help_text="E.g. '07987 654 321' or '0041 234 56 78 90'", max_length=18)),
                ('address_line_1', models.CharField(help_text='E.g. 221b Baker Street', max_length=64)),
                ('address_line_2', models.CharField(blank=True, help_text='E.g. Muswell Hill', max_length=64)),
                ('city', models.CharField(help_text='E.g. London', max_length=32)),
                ('postcode', models.CharField(help_text='E.g. CL12 321', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='E.g. University of Bristol', max_length=64)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField()),
                ('qualification', models.CharField(help_text='E.g. BA Media Studies', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Piano', max_length=32)),
                ('detail', models.TextField(blank=True, help_text='E.g. Grade 5')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.DateField(help_text='Date of first performance.')),
                ('final', models.DateField(help_text='Date of final performance.')),
                ('performance', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('director', models.CharField(blank=True, max_length=32)),
                ('venue', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=32)),
                ('hidden', models.BooleanField(default=False)),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Gallery')),
            ],
        ),
    ]
