# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='E.g. 221b Baker Street', max_length=64),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, help_text='E.g. patrickstewart@gmail.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='postcode',
            field=models.CharField(blank=True, help_text='E.g. CL12 321', max_length=8),
        ),
    ]
