# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160412_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
