# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20160413_1212'),
        ('homepage', '0004_auto_20160413_2321'),
    ]

    operations = [
    ]
