# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20160413_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
