# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_merge'),
        ('homepage', '0005_auto_20160625_2048'),
    ]

    operations = [
    ]
