# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='spotlight',
            field=models.URLField(blank=True, help_text='Link to your Spotlight profile'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, help_text='E.g. sherlock_holmes@gmail.com', max_length=128),
        ),
    ]
