# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_contactdetail_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='ContactDetails',
        ),
    ]
