# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20160705_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='city',
            field=models.CharField(blank=True, help_text='E.g. London', max_length=32),
        ),
    ]
