# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_showreel'),
    ]

    operations = [
        migrations.AddField(
            model_name='showreel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='showreel',
            name='title',
            field=models.CharField(default='Video editing masterclass', max_length=64),
            preserve_default=False,
        ),
    ]
